{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72dfba73",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'topology.pdb'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mFileNotFoundError\u001b[39m                         Traceback (most recent call last)",
      "    \u001b[31m[... skipping hidden 1 frame]\u001b[39m\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mMDAnalysis\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mmda\u001b[39;00m \n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m u = \u001b[43mmda\u001b[49m\u001b[43m.\u001b[49m\u001b[43mUniverse\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtopology.pdb\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43msamples.xtc\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      6\u001b[39m view = visualize_mda_universe(u)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:417\u001b[39m, in \u001b[36mUniverse.__init__\u001b[39m\u001b[34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, context, to_guess, force_guess, in_memory_step, *coordinates, **kwargs)\u001b[39m\n\u001b[32m    416\u001b[39m     \u001b[38;5;28mself\u001b[39m.filename = _check_file_like(topology)\n\u001b[32m--> \u001b[39m\u001b[32m417\u001b[39m     topology = \u001b[43m_topology_from_file_like\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    418\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    419\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    421\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m topology \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:121\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    118\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m (err.errno \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[32m    119\u001b[39m     errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m'\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m'\u001b[39m]):\n\u001b[32m    120\u001b[39m     \u001b[38;5;66;03m# Runs if the error is propagated due to no permission / file not found\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m121\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    122\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    123\u001b[39m     \u001b[38;5;66;03m# Runs when the parser fails\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:113\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    112\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m parser(topology_file) \u001b[38;5;28;01mas\u001b[39;00m p:\n\u001b[32m--> \u001b[39m\u001b[32m113\u001b[39m         topology = \u001b[43mp\u001b[49m\u001b[43m.\u001b[49m\u001b[43mparse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    114\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    115\u001b[39m     \u001b[38;5;66;03m# There are 2 kinds of errors that might be raised here:\u001b[39;00m\n\u001b[32m    116\u001b[39m     \u001b[38;5;66;03m# one because the file isn't present\u001b[39;00m\n\u001b[32m    117\u001b[39m     \u001b[38;5;66;03m# or the permissions are bad, second when the parser fails\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:215\u001b[39m, in \u001b[36mPDBParser.parse\u001b[39m\u001b[34m(self, **kwargs)\u001b[39m\n\u001b[32m    209\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Parse atom information from PDB file\u001b[39;00m\n\u001b[32m    210\u001b[39m \n\u001b[32m    211\u001b[39m \u001b[33;03mReturns\u001b[39;00m\n\u001b[32m    212\u001b[39m \u001b[33;03m-------\u001b[39;00m\n\u001b[32m    213\u001b[39m \u001b[33;03mMDAnalysis Topology object\u001b[39;00m\n\u001b[32m    214\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m215\u001b[39m top = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_parseatoms\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    217\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:252\u001b[39m, in \u001b[36mPDBParser._parseatoms\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    251\u001b[39m last_wrapped_serial = \u001b[32m100000\u001b[39m  \u001b[38;5;66;03m# if serials wrap, start from here\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m252\u001b[39m \u001b[43m\u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43mopenany\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mas\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m    253\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mline\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/contextlib.py:137\u001b[39m, in \u001b[36m_GeneratorContextManager.__enter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    136\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m137\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mnext\u001b[39m(\u001b[38;5;28mself\u001b[39m.gen)\n\u001b[32m    138\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:326\u001b[39m, in \u001b[36mopenany\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    284\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Context manager for :func:`anyopen`.\u001b[39;00m\n\u001b[32m    285\u001b[39m \n\u001b[32m    286\u001b[39m \u001b[33;03mOpen the `datasource` and close it when the context of the :keyword:`with`\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    324\u001b[39m \u001b[33;03m:func:`anyopen`\u001b[39;00m\n\u001b[32m    325\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m326\u001b[39m stream = \u001b[43manyopen\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreset\u001b[49m\u001b[43m=\u001b[49m\u001b[43mreset\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    327\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:408\u001b[39m, in \u001b[36manyopen\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    407\u001b[39m openfunc = read_handlers[ext]\n\u001b[32m--> \u001b[39m\u001b[32m408\u001b[39m stream = \u001b[43m_get_stream\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mopenfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    409\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m stream \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:468\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    467\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m\"\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m\"\u001b[39m]:\n\u001b[32m--> \u001b[39m\u001b[32m468\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    469\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:462\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    461\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m462\u001b[39m     stream = \u001b[43mopenfunction\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    463\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    464\u001b[39m     \u001b[38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this\u001b[39;00m\n\u001b[32m    465\u001b[39m     \u001b[38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because\u001b[39;00m\n\u001b[32m    466\u001b[39m     \u001b[38;5;66;03m# either the file isn't there or the permissions don't allow access.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:540\u001b[39m, in \u001b[36mbz2_pickle_open\u001b[39m\u001b[34m(name, mode)\u001b[39m\n\u001b[32m    539\u001b[39m bz_mode = mode.replace(\u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m540\u001b[39m binary_file = \u001b[43mBZ2Picklable\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbz_mode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    541\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m mode:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:309\u001b[39m, in \u001b[36mBZ2Picklable.__init__\u001b[39m\u001b[34m(self, name, mode)\u001b[39m\n\u001b[32m    308\u001b[39m \u001b[38;5;28mself\u001b[39m._bz_mode = mode\n\u001b[32m--> \u001b[39m\u001b[32m309\u001b[39m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/bz2.py:81\u001b[39m, in \u001b[36mBZ2File.__init__\u001b[39m\u001b[34m(self, filename, mode, compresslevel)\u001b[39m\n\u001b[32m     80\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(filename, (\u001b[38;5;28mstr\u001b[39m, \u001b[38;5;28mbytes\u001b[39m, os.PathLike)):\n\u001b[32m---> \u001b[39m\u001b[32m81\u001b[39m     \u001b[38;5;28mself\u001b[39m._fp = \u001b[43m_builtin_open\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     82\u001b[39m     \u001b[38;5;28mself\u001b[39m._closefp = \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "\u001b[31mFileNotFoundError\u001b[39m: [Errno 2] No such file or directory: 'topology.pdb'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mFileNotFoundError\u001b[39m                         Traceback (most recent call last)",
      "    \u001b[31m[... skipping hidden 1 frame]\u001b[39m\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mMDAnalysis\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mmda\u001b[39;00m \n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m u = \u001b[43mmda\u001b[49m\u001b[43m.\u001b[49m\u001b[43mUniverse\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtopology.pdb\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43msamples.xtc\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      6\u001b[39m view = visualize_mda_universe(u)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:417\u001b[39m, in \u001b[36mUniverse.__init__\u001b[39m\u001b[34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, context, to_guess, force_guess, in_memory_step, *coordinates, **kwargs)\u001b[39m\n\u001b[32m    416\u001b[39m     \u001b[38;5;28mself\u001b[39m.filename = _check_file_like(topology)\n\u001b[32m--> \u001b[39m\u001b[32m417\u001b[39m     topology = \u001b[43m_topology_from_file_like\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    418\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    419\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    421\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m topology \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:121\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    118\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m (err.errno \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[32m    119\u001b[39m     errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m'\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m'\u001b[39m]):\n\u001b[32m    120\u001b[39m     \u001b[38;5;66;03m# Runs if the error is propagated due to no permission / file not found\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m121\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    122\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    123\u001b[39m     \u001b[38;5;66;03m# Runs when the parser fails\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:113\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    112\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m parser(topology_file) \u001b[38;5;28;01mas\u001b[39;00m p:\n\u001b[32m--> \u001b[39m\u001b[32m113\u001b[39m         topology = \u001b[43mp\u001b[49m\u001b[43m.\u001b[49m\u001b[43mparse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    114\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    115\u001b[39m     \u001b[38;5;66;03m# There are 2 kinds of errors that might be raised here:\u001b[39;00m\n\u001b[32m    116\u001b[39m     \u001b[38;5;66;03m# one because the file isn't present\u001b[39;00m\n\u001b[32m    117\u001b[39m     \u001b[38;5;66;03m# or the permissions are bad, second when the parser fails\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:215\u001b[39m, in \u001b[36mPDBParser.parse\u001b[39m\u001b[34m(self, **kwargs)\u001b[39m\n\u001b[32m    209\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Parse atom information from PDB file\u001b[39;00m\n\u001b[32m    210\u001b[39m \n\u001b[32m    211\u001b[39m \u001b[33;03mReturns\u001b[39;00m\n\u001b[32m    212\u001b[39m \u001b[33;03m-------\u001b[39;00m\n\u001b[32m    213\u001b[39m \u001b[33;03mMDAnalysis Topology object\u001b[39;00m\n\u001b[32m    214\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m215\u001b[39m top = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_parseatoms\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    217\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:252\u001b[39m, in \u001b[36mPDBParser._parseatoms\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    251\u001b[39m last_wrapped_serial = \u001b[32m100000\u001b[39m  \u001b[38;5;66;03m# if serials wrap, start from here\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m252\u001b[39m \u001b[43m\u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43mopenany\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mas\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m    253\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mline\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/contextlib.py:137\u001b[39m, in \u001b[36m_GeneratorContextManager.__enter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    136\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m137\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mnext\u001b[39m(\u001b[38;5;28mself\u001b[39m.gen)\n\u001b[32m    138\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:326\u001b[39m, in \u001b[36mopenany\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    284\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Context manager for :func:`anyopen`.\u001b[39;00m\n\u001b[32m    285\u001b[39m \n\u001b[32m    286\u001b[39m \u001b[33;03mOpen the `datasource` and close it when the context of the :keyword:`with`\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    324\u001b[39m \u001b[33;03m:func:`anyopen`\u001b[39;00m\n\u001b[32m    325\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m326\u001b[39m stream = \u001b[43manyopen\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreset\u001b[49m\u001b[43m=\u001b[49m\u001b[43mreset\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    327\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:408\u001b[39m, in \u001b[36manyopen\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    407\u001b[39m openfunc = read_handlers[ext]\n\u001b[32m--> \u001b[39m\u001b[32m408\u001b[39m stream = \u001b[43m_get_stream\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mopenfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    409\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m stream \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:468\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    467\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m\"\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m\"\u001b[39m]:\n\u001b[32m--> \u001b[39m\u001b[32m468\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    469\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:462\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    461\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m462\u001b[39m     stream = \u001b[43mopenfunction\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    463\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    464\u001b[39m     \u001b[38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this\u001b[39;00m\n\u001b[32m    465\u001b[39m     \u001b[38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because\u001b[39;00m\n\u001b[32m    466\u001b[39m     \u001b[38;5;66;03m# either the file isn't there or the permissions don't allow access.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:540\u001b[39m, in \u001b[36mbz2_pickle_open\u001b[39m\u001b[34m(name, mode)\u001b[39m\n\u001b[32m    539\u001b[39m bz_mode = mode.replace(\u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m540\u001b[39m binary_file = \u001b[43mBZ2Picklable\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbz_mode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    541\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m mode:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:309\u001b[39m, in \u001b[36mBZ2Picklable.__init__\u001b[39m\u001b[34m(self, name, mode)\u001b[39m\n\u001b[32m    308\u001b[39m \u001b[38;5;28mself\u001b[39m._bz_mode = mode\n\u001b[32m--> \u001b[39m\u001b[32m309\u001b[39m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/bz2.py:81\u001b[39m, in \u001b[36mBZ2File.__init__\u001b[39m\u001b[34m(self, filename, mode, compresslevel)\u001b[39m\n\u001b[32m     80\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(filename, (\u001b[38;5;28mstr\u001b[39m, \u001b[38;5;28mbytes\u001b[39m, os.PathLike)):\n\u001b[32m---> \u001b[39m\u001b[32m81\u001b[39m     \u001b[38;5;28mself\u001b[39m._fp = \u001b[43m_builtin_open\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     82\u001b[39m     \u001b[38;5;28mself\u001b[39m._closefp = \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "\u001b[31mFileNotFoundError\u001b[39m: [Errno 2] No such file or directory: 'topology.pdb'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mFileNotFoundError\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mvisualize\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m visualize_mda_universe \u001b[38;5;66;03m# local file\u001b[39;00m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mMDAnalysis\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mmda\u001b[39;00m \n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m u = \u001b[43mmda\u001b[49m\u001b[43m.\u001b[49m\u001b[43mUniverse\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtopology.pdb\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43msamples.xtc\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      6\u001b[39m view = visualize_mda_universe(u)\n\u001b[32m      7\u001b[39m view.show()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:417\u001b[39m, in \u001b[36mUniverse.__init__\u001b[39m\u001b[34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, context, to_guess, force_guess, in_memory_step, *coordinates, **kwargs)\u001b[39m\n\u001b[32m    415\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(topology, Topology) \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m topology \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    416\u001b[39m     \u001b[38;5;28mself\u001b[39m.filename = _check_file_like(topology)\n\u001b[32m--> \u001b[39m\u001b[32m417\u001b[39m     topology = \u001b[43m_topology_from_file_like\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    418\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtopology_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    419\u001b[39m \u001b[43m                                        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    421\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m topology \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    422\u001b[39m     \u001b[38;5;28mself\u001b[39m._topology = topology\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:121\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    114\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    115\u001b[39m     \u001b[38;5;66;03m# There are 2 kinds of errors that might be raised here:\u001b[39;00m\n\u001b[32m    116\u001b[39m     \u001b[38;5;66;03m# one because the file isn't present\u001b[39;00m\n\u001b[32m    117\u001b[39m     \u001b[38;5;66;03m# or the permissions are bad, second when the parser fails\u001b[39;00m\n\u001b[32m    118\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m (err.errno \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[32m    119\u001b[39m         errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m'\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m'\u001b[39m]):\n\u001b[32m    120\u001b[39m         \u001b[38;5;66;03m# Runs if the error is propagated due to no permission / file not found\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m121\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    122\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    123\u001b[39m         \u001b[38;5;66;03m# Runs when the parser fails\u001b[39;00m\n\u001b[32m    124\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mIOError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mFailed to load from the topology file \u001b[39m\u001b[38;5;132;01m{0}\u001b[39;00m\u001b[33m\"\u001b[39m\n\u001b[32m    125\u001b[39m                         \u001b[33m\"\u001b[39m\u001b[33m with parser \u001b[39m\u001b[38;5;132;01m{1}\u001b[39;00m\u001b[33m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[33m\"\u001b[39m\n\u001b[32m    126\u001b[39m                         \u001b[33m\"\u001b[39m\u001b[33mError: \u001b[39m\u001b[38;5;132;01m{2}\u001b[39;00m\u001b[33m\"\u001b[39m.format(topology_file, parser, err))\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/core/universe.py:113\u001b[39m, in \u001b[36m_topology_from_file_like\u001b[39m\u001b[34m(topology_file, topology_format, **kwargs)\u001b[39m\n\u001b[32m    111\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    112\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m parser(topology_file) \u001b[38;5;28;01mas\u001b[39;00m p:\n\u001b[32m--> \u001b[39m\u001b[32m113\u001b[39m         topology = \u001b[43mp\u001b[49m\u001b[43m.\u001b[49m\u001b[43mparse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    114\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    115\u001b[39m     \u001b[38;5;66;03m# There are 2 kinds of errors that might be raised here:\u001b[39;00m\n\u001b[32m    116\u001b[39m     \u001b[38;5;66;03m# one because the file isn't present\u001b[39;00m\n\u001b[32m    117\u001b[39m     \u001b[38;5;66;03m# or the permissions are bad, second when the parser fails\u001b[39;00m\n\u001b[32m    118\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m (err.errno \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[32m    119\u001b[39m         errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m'\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m'\u001b[39m]):\n\u001b[32m    120\u001b[39m         \u001b[38;5;66;03m# Runs if the error is propagated due to no permission / file not found\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:215\u001b[39m, in \u001b[36mPDBParser.parse\u001b[39m\u001b[34m(self, **kwargs)\u001b[39m\n\u001b[32m    208\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mparse\u001b[39m(\u001b[38;5;28mself\u001b[39m, **kwargs):\n\u001b[32m    209\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Parse atom information from PDB file\u001b[39;00m\n\u001b[32m    210\u001b[39m \n\u001b[32m    211\u001b[39m \u001b[33;03m    Returns\u001b[39;00m\n\u001b[32m    212\u001b[39m \u001b[33;03m    -------\u001b[39;00m\n\u001b[32m    213\u001b[39m \u001b[33;03m    MDAnalysis Topology object\u001b[39;00m\n\u001b[32m    214\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m215\u001b[39m     top = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_parseatoms\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    217\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    218\u001b[39m         bonds = \u001b[38;5;28mself\u001b[39m._parsebonds(top.ids.values)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:252\u001b[39m, in \u001b[36mPDBParser._parseatoms\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    250\u001b[39m \u001b[38;5;28mself\u001b[39m._wrapped_serials = \u001b[38;5;28;01mFalse\u001b[39;00m  \u001b[38;5;66;03m# did serials go over 100k?\u001b[39;00m\n\u001b[32m    251\u001b[39m last_wrapped_serial = \u001b[32m100000\u001b[39m  \u001b[38;5;66;03m# if serials wrap, start from here\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m252\u001b[39m \u001b[43m\u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43mopenany\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mas\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m    253\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mline\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m    254\u001b[39m \u001b[43m        \u001b[49m\u001b[43mline\u001b[49m\u001b[43m \u001b[49m\u001b[43m=\u001b[49m\u001b[43m \u001b[49m\u001b[43mline\u001b[49m\u001b[43m.\u001b[49m\u001b[43mstrip\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Remove extra spaces\u001b[39;49;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/contextlib.py:137\u001b[39m, in \u001b[36m_GeneratorContextManager.__enter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    135\u001b[39m \u001b[38;5;28;01mdel\u001b[39;00m \u001b[38;5;28mself\u001b[39m.args, \u001b[38;5;28mself\u001b[39m.kwds, \u001b[38;5;28mself\u001b[39m.func\n\u001b[32m    136\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m137\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mnext\u001b[39m(\u001b[38;5;28mself\u001b[39m.gen)\n\u001b[32m    138\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m:\n\u001b[32m    139\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mgenerator didn\u001b[39m\u001b[33m'\u001b[39m\u001b[33mt yield\u001b[39m\u001b[33m\"\u001b[39m) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:326\u001b[39m, in \u001b[36mopenany\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    282\u001b[39m \u001b[38;5;129m@contextmanager\u001b[39m\n\u001b[32m    283\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mopenany\u001b[39m(datasource, mode=\u001b[33m\"\u001b[39m\u001b[33mrt\u001b[39m\u001b[33m\"\u001b[39m, reset=\u001b[38;5;28;01mTrue\u001b[39;00m):\n\u001b[32m    284\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Context manager for :func:`anyopen`.\u001b[39;00m\n\u001b[32m    285\u001b[39m \n\u001b[32m    286\u001b[39m \u001b[33;03m    Open the `datasource` and close it when the context of the :keyword:`with`\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    324\u001b[39m \u001b[33;03m    :func:`anyopen`\u001b[39;00m\n\u001b[32m    325\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m326\u001b[39m     stream = \u001b[43manyopen\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreset\u001b[49m\u001b[43m=\u001b[49m\u001b[43mreset\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    327\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    328\u001b[39m         \u001b[38;5;28;01myield\u001b[39;00m stream\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:408\u001b[39m, in \u001b[36manyopen\u001b[39m\u001b[34m(datasource, mode, reset)\u001b[39m\n\u001b[32m    406\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m ext \u001b[38;5;129;01min\u001b[39;00m (\u001b[33m\"\u001b[39m\u001b[33mbz2\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mgz\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m):  \u001b[38;5;66;03m# file == '' should be last\u001b[39;00m\n\u001b[32m    407\u001b[39m     openfunc = read_handlers[ext]\n\u001b[32m--> \u001b[39m\u001b[32m408\u001b[39m     stream = \u001b[43m_get_stream\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdatasource\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mopenfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    409\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m stream \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    410\u001b[39m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:468\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    463\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    464\u001b[39m     \u001b[38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this\u001b[39;00m\n\u001b[32m    465\u001b[39m     \u001b[38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because\u001b[39;00m\n\u001b[32m    466\u001b[39m     \u001b[38;5;66;03m# either the file isn't there or the permissions don't allow access.\u001b[39;00m\n\u001b[32m    467\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m\"\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m\"\u001b[39m]:\n\u001b[32m--> \u001b[39m\u001b[32m468\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m sys.exc_info()[\u001b[32m1\u001b[39m] \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01merr\u001b[39;00m\n\u001b[32m    469\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    470\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m mode.startswith(\u001b[33m\"\u001b[39m\u001b[33mr\u001b[39m\u001b[33m\"\u001b[39m):\n\u001b[32m    471\u001b[39m     \u001b[38;5;66;03m# additional check for reading (eg can we uncompress) --- is this needed?\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/util.py:462\u001b[39m, in \u001b[36m_get_stream\u001b[39m\u001b[34m(filename, openfunction, mode)\u001b[39m\n\u001b[32m    460\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Return open stream if *filename* can be opened with *openfunction* or else ``None``.\"\"\"\u001b[39;00m\n\u001b[32m    461\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m462\u001b[39m     stream = \u001b[43mopenfunction\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m=\u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    463\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mIOError\u001b[39;00m, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[32m    464\u001b[39m     \u001b[38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this\u001b[39;00m\n\u001b[32m    465\u001b[39m     \u001b[38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because\u001b[39;00m\n\u001b[32m    466\u001b[39m     \u001b[38;5;66;03m# either the file isn't there or the permissions don't allow access.\u001b[39;00m\n\u001b[32m    467\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m errno.errorcode[err.errno] \u001b[38;5;129;01min\u001b[39;00m [\u001b[33m\"\u001b[39m\u001b[33mENOENT\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mEACCES\u001b[39m\u001b[33m\"\u001b[39m]:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:540\u001b[39m, in \u001b[36mbz2_pickle_open\u001b[39m\u001b[34m(name, mode)\u001b[39m\n\u001b[32m    536\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m    537\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mOnly read mode (\u001b[39m\u001b[33m'\u001b[39m\u001b[33mr\u001b[39m\u001b[33m'\u001b[39m\u001b[33m, \u001b[39m\u001b[33m'\u001b[39m\u001b[33mrt\u001b[39m\u001b[33m'\u001b[39m\u001b[33m, \u001b[39m\u001b[33m'\u001b[39m\u001b[33mrb\u001b[39m\u001b[33m'\u001b[39m\u001b[33m) \u001b[39m\u001b[33m\"\u001b[39m \u001b[33m\"\u001b[39m\u001b[33mfiles can be pickled.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    538\u001b[39m     )\n\u001b[32m    539\u001b[39m bz_mode = mode.replace(\u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m540\u001b[39m binary_file = \u001b[43mBZ2Picklable\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbz_mode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    541\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[33m\"\u001b[39m\u001b[33mt\u001b[39m\u001b[33m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m mode:\n\u001b[32m    542\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m TextIOPicklable(binary_file)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/capstone/.venv/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:309\u001b[39m, in \u001b[36mBZ2Picklable.__init__\u001b[39m\u001b[34m(self, name, mode)\u001b[39m\n\u001b[32m    307\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__init__\u001b[39m(\u001b[38;5;28mself\u001b[39m, name, mode=\u001b[33m\"\u001b[39m\u001b[33mrb\u001b[39m\u001b[33m\"\u001b[39m):\n\u001b[32m    308\u001b[39m     \u001b[38;5;28mself\u001b[39m._bz_mode = mode\n\u001b[32m--> \u001b[39m\u001b[32m309\u001b[39m     \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/lib/python3.11/bz2.py:81\u001b[39m, in \u001b[36mBZ2File.__init__\u001b[39m\u001b[34m(self, filename, mode, compresslevel)\u001b[39m\n\u001b[32m     78\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mInvalid mode: \u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[33m\"\u001b[39m % (mode,))\n\u001b[32m     80\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(filename, (\u001b[38;5;28mstr\u001b[39m, \u001b[38;5;28mbytes\u001b[39m, os.PathLike)):\n\u001b[32m---> \u001b[39m\u001b[32m81\u001b[39m     \u001b[38;5;28mself\u001b[39m._fp = \u001b[43m_builtin_open\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     82\u001b[39m     \u001b[38;5;28mself\u001b[39m._closefp = \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[32m     83\u001b[39m     \u001b[38;5;28mself\u001b[39m._mode = mode_code\n",
      "\u001b[31mFileNotFoundError\u001b[39m: [Errno 2] No such file or directory: 'topology.pdb'"
     ]
    }
   ],
   "source": [
    "from visualize import visualize_mda_universe # local file\n",
    "\n",
    "import MDAnalysis as mda \n",
    "\n",
    "u = mda.Universe(\"test-bioemu-ubq/topology.pdb\", \"test-bioemu-ubq/samples.xtc\")\n",
    "view = visualize_mda_universe(u)\n",
    "view.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e46b6804",
   "metadata": {},
   "outputs": [],
   "source": [
    "import rmsd_for_atom_groups as rmsd\n",
    "\n",
    "rmsd.rmsd_for_atomgroups(u, selection1=\"backbone\", selection2=[\"protein\"])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f25d68d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from MDAnalysis.analysis import rms\n",
    "\n",
    "selection1 = \"backbone\"\n",
    "selection2 = [\"protein\"]\n",
    "\n",
    "print(len(u.trajectory))\n",
    "u.trajectory[0]\n",
    "ref = u\n",
    "rmsd_analysis = rms.RMSD(u, ref, select=selection1, groupselections=selection2)\n",
    "rmsd_analysis.run()\n",
    "columns = [selection1, *selection2] if selection2 else [selection1]\n",
    "rmsd_df = pd.DataFrame(np.round(rmsd_analysis.rmsd[:, 2:], 2), columns=columns)\n",
    "rmsd_df.index.name = \"Frame\"\n",
    "rmsd_df.head()\n",
    "\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "rmsd_df.plot(title=\"RMSD of protein\")\n",
    "plt.ylabel(\"RMSD (Angstrom)\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eef4713f",
   "metadata": {},
   "source": [
    "to go:\n",
    "1) distance maps\n",
    "2) see if the conformations sampled represent the peptide flip phenomenon in ubiquitin"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b8a78539",
   "metadata": {},
   "source": [
    "for distance maps there is a function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cbb994a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from MDAnalysis.analysis import diffusionmap\n",
    "\n",
    "pairwise_rmsd = diffusionmap.DistanceMatrix(u, select=\"protein\")\n",
    "pairwise_rmsd.run()\n",
    "dist_matrix_protein = pairwise_rmsd.dist_matrix\n",
    "max_dist = np.amax(dist_matrix_protein)\n",
    "\n",
    "\n",
    "\n",
    "fig, ax = plt.subplots(1,1)\n",
    "fig.suptitle(\"RMSD between the frames\")\n",
    "\n",
    "# protein image\n",
    "img1 = ax.imshow(dist_matrix_protein, cmap=\"viridis\", vmin=0, vmax=max_dist)\n",
    "ax.title.set_text(\"protein\")\n",
    "ax.set_xlabel(\"frames\")\n",
    "ax.set_ylabel(\"frames\")\n",
    "\n",
    "\n",
    "fig.colorbar(img1, ax=ax, orientation=\"horizontal\", fraction=0.1, label=\"RMSD (Å)\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
